{
 "title": "Leader Board",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "difficulties", "label": "Difficulty", "query": "1,2,3,4,5,6" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">Presidio Juice Shop Leader Board</h1>\n         "
   }
  },
  {
   "title": "Score by Team",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum without (category,difficulty)(juiceshop_challenges_solved{ difficulty=\"1\"}) * 100) + \n(sum without (category,difficulty)(juiceshop_challenges_solved{ difficulty=\"2\"}) * 200) +\n(sum without (category,difficulty)(juiceshop_challenges_solved{ difficulty=\"3\"}) * 300) +\n(sum without (category,difficulty)(juiceshop_challenges_solved{ difficulty=\"4\"}) * 400) +\n(sum without (category,difficulty)(juiceshop_challenges_solved{ difficulty=\"5\"}) * 500) +\n(sum without (category,difficulty)(juiceshop_challenges_solved{ difficulty=\"6\"}) * 600)\n",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Challenges solve by Team",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (category,difficulty)(juiceshop_challenges_solved)",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Total Number of Challenges Solved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(juiceshop_challenges_solved)",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_count{app=\"juiceshop\"}[1m])",
     "legendFormat": "{{team}} - {{status_code}}"
    }
   ]
  },
  { "title": "Total Challenges by Difficulty", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$difficulties Star Challenges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
   "repeat": "difficulties",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(juiceshop_challenges_solved{difficulty=\"$difficulties\"})"
    }
   ]
  },
  {
   "title": "$difficulties Star Challenges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(juiceshop_challenges_solved{difficulty=\"$difficulties\"})"
    }
   ]
  },
  {
   "title": "$difficulties Star Challenges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(juiceshop_challenges_solved{difficulty=\"$difficulties\"})"
    }
   ]
  },
  {
   "title": "$difficulties Star Challenges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(juiceshop_challenges_solved{difficulty=\"$difficulties\"})"
    }
   ]
  },
  {
   "title": "$difficulties Star Challenges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(juiceshop_challenges_solved{difficulty=\"$difficulties\"})"
    }
   ]
  },
  {
   "title": "$difficulties Star Challenges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(juiceshop_challenges_solved{difficulty=\"$difficulties\"})"
    }
   ]
  },
  {
   "title": "Challenges solved by Category",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category)(juiceshop_challenges_solved) != 0",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}