name: 'Publish Helm Charts'

on:
  push:
    branches:
      - presidio

jobs:
  helmRelease:
    name: 'Package Helm Chart'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@v2.0.0
        with:
          access-token: ${{ secrets.CR_TOKEN }}
          charts-folder: helm
          deploy-branch: gh-pages